### ISSUE TITLE
error while executing a package developed by installjammer

### ISSUE THREAD

**Issue by poorani** [damoncourtney/installjammer#11] opened 2010-07-21 04:43 UTC
i ve developed a software for which packaging is done by installjammer.. it worked well in redhat linux... but in redhat linux which has been invoked from windows thru Xserver i cudn ve any option to doubleclick..so i ve executed it from console... then it throwed this error

unknown color name "white"
   (database entry for "-background" in widget ".#BWidget.#Class#listbox")
   invoked from within
"$command $path"
   (procedure "Widget::CreateTempWidget" line 11)
   invoked from within
"Widget::CreateTempWidget $tkwidget $tkwidget"
   (procedure "Widget::declare" line 61)
   invoked from within
"Widget::declare Tree {
{-deltax            Int        10       0 "%d >= 0"}
{-deltay            Int        15       0 "%d >= 0"}
{-padx              I..."
   (in namespace eval "::Tree" script line 37)
   invoked from within
"namespace eval Tree {
Widget::define Tree tree DragSite DropSite DynamicHelp

namespace eval Node {
Widget::declare Tree::Node {
{-text       String  ..."
   (procedure "InitGui" line 2862)
   invoked from within
"InitGui"
   (procedure "::InstallJammer::InitInstall" line 66)
   invoked from within
"::InstallJammer::InitInstall"
   (file "/installkitvfs/main.tcl" line 30581)

what is the problem...?

can you reply fast ?
even ucan send my reply to pooranimuthusamy@gmail.com
i had to fix this problem soon to finish my project

**Comment by damoncourtney** [comment] 2010-07-21 05:13
The problem is that the X server does not recognize "white" as a color.  I actually just looked at this tonight as part of some bugs I'm fixing.  The only fix, really, is to remove all references to specific color names within the software and replace them with there hex RGB values.

I can commit something tomorrow to fix this problem, but if you need a fix now, you'll have to grep through the entire source base and look for the word "white" and replace it with #FFFFFF anywhere you see it.  If you can wait, I'll fix this tomorrow.

**Comment by damoncourtney** [comment] 2010-07-22 20:47
I committed a fix for this.  Should be resolved.

**Closed as completed by damoncourtney** 2010-07-22 20:47 UTC
